<?php

namespace App;

use OpenApi\Attributes as OA;

#[OA\Info(version: '1.0.0', title: 'POS System API', description: 'توثيق واجهات نظام نقاط البيع. تستخدم الواجهات المحمية Laravel Sanctum Bearer Token.')]
#[OA\Server(url: '/', description: 'الخادم الحالي')]
#[OA\SecurityScheme(securityScheme: 'sanctum', type: 'http', scheme: 'bearer', bearerFormat: 'Sanctum token', description: 'ألصق التوكن فقط؛ Swagger يضيف Bearer تلقائياً.')]
#[OA\Components(requestBodies: [
    new OA\RequestBody(request: 'JsonBody', required: true, content: new OA\JsonContent(type: 'object', additionalProperties: true)),
    new OA\RequestBody(request: 'LoginBody', required: true, content: new OA\JsonContent(type: 'object', example: ['email' => 'admin@example.com', 'password' => 'password', 'device_name' => 'Swagger'])),
    new OA\RequestBody(request: 'ProductBody', required: true, content: new OA\MediaType(mediaType: 'multipart/form-data', schema: new OA\Schema(type: 'object', properties: [new OA\Property(property: 'product_name', type: 'string'), new OA\Property(property: 'sku', type: 'string'), new OA\Property(property: 'barcode', type: 'string', nullable: true), new OA\Property(property: 'type', type: 'string', enum: ['stock', 'service']), new OA\Property(property: 'unit_id', type: 'string', format: 'uuid'), new OA\Property(property: 'category_id', type: 'string', format: 'uuid'), new OA\Property(property: 'tax_id', type: 'string', format: 'uuid', nullable: true), new OA\Property(property: 'cost_price', type: 'number'), new OA\Property(property: 'price', type: 'number'), new OA\Property(property: 'image', type: 'string', format: 'binary', nullable: true), new OA\Property(property: 'warehouse_id', type: 'string', format: 'uuid', nullable: true), new OA\Property(property: 'opening_quantity', type: 'number', nullable: true), new OA\Property(property: 'reorder_level', type: 'number', nullable: true)]))),
])]
#[OA\Post(path: '/v1/login', operationId: 'login', summary: 'تسجيل الدخول وإصدار توكن', tags: ['Auth'], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/LoginBody'), responses: [new OA\Response(response: 200, description: 'تم تسجيل الدخول'), new OA\Response(response: 422, description: 'بيانات غير صحيحة'), new OA\Response(response: 429, description: 'محاولات كثيرة')])]
#[OA\Get(path: '/v1/me', operationId: 'me', summary: 'المستخدم الحالي وأدواره وصلاحياته', tags: ['Auth'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'بيانات المستخدم')])]
#[OA\Post(path: '/v1/logout', operationId: 'logout', summary: 'إلغاء التوكن الحالي', tags: ['Auth'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'تم تسجيل الخروج')])]
#[OA\Post(path: '/v1/logout-all', operationId: 'logoutAll', summary: 'إلغاء جميع توكنات المستخدم', tags: ['Auth'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'تم تسجيل الخروج من كل الأجهزة')])]
#[OA\Post(path: '/v1/password/change', operationId: 'changePassword', summary: 'تغيير كلمة المرور', tags: ['Auth'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم تغيير كلمة المرور'), new OA\Response(response: 422, description: 'فشل التحقق')])]
#[OA\Get(path: '/v1/categories', operationId: 'categoriesIndex', summary: 'عرض شجرة التصنيفات', tags: ['Categories'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'قائمة التصنيفات')])]
#[OA\Post(path: '/v1/categories', operationId: 'categoriesStore', summary: 'إنشاء تصنيف', tags: ['Categories'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم الإنشاء')])]
#[OA\Get(path: '/v1/categories/{category}', operationId: 'categoriesShow', summary: 'عرض تصنيف', tags: ['Categories'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'category', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل التصنيف')])]
#[OA\Put(path: '/v1/categories/{category}', operationId: 'categoriesUpdatePut', summary: 'تعديل تصنيف', tags: ['Categories'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'category', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Patch(path: '/v1/categories/{category}', operationId: 'categoriesUpdatePatch', summary: 'تعديل جزئي لتصنيف', tags: ['Categories'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'category', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Delete(path: '/v1/categories/{category}', operationId: 'categoriesDestroy', summary: 'حذف تصنيف', tags: ['Categories'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'category', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تم الحذف')])]
#[OA\Get(path: '/v1/products', operationId: 'productsIndex', summary: 'البحث وعرض المنتجات', tags: ['Products'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'search', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'category_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'warehouse_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'type', in: 'query', schema: new OA\Schema(type: 'string', enum: ['stock', 'service'])), new OA\Parameter(name: 'low_stock', in: 'query', schema: new OA\Schema(type: 'boolean')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 10, maximum: 100))], responses: [new OA\Response(response: 200, description: 'قائمة المنتجات')])]
#[OA\Post(path: '/v1/products', operationId: 'productsStore', summary: 'إنشاء منتج أو خدمة', tags: ['Products'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/ProductBody'), responses: [new OA\Response(response: 201, description: 'تم الإنشاء')])]
#[OA\Get(path: '/v1/products/{product}', operationId: 'productsShow', summary: 'عرض منتج', tags: ['Products'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'product', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل المنتج')])]
#[OA\Put(path: '/v1/products/{product}', operationId: 'productsUpdatePut', summary: 'تعديل منتج', tags: ['Products'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'product', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/ProductBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Patch(path: '/v1/products/{product}', operationId: 'productsUpdatePatch', summary: 'تعديل جزئي لمنتج', tags: ['Products'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'product', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/ProductBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Delete(path: '/v1/products/{product}', operationId: 'productsDestroy', summary: 'حذف منتج', tags: ['Products'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'product', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تم الحذف')])]
#[OA\Post(path: '/v1/products/{product}/fetch-image', operationId: 'productsFetchImage', summary: 'جلب صورة للمنتج', tags: ['Products'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'product', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تم جلب الصورة')])]
#[OA\Get(path: '/v1/customers', operationId: 'customersIndex', summary: 'عرض العملاء', tags: ['Customers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'search', in: 'query', description: 'بحث بالاسم أو الشركة أو الهاتف أو البريد أو الرقم الضريبي', schema: new OA\Schema(type: 'string', maxLength: 100)), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 25))], responses: [new OA\Response(response: 200, description: 'قائمة العملاء مع بيانات الصفحات'), new OA\Response(response: 422, description: 'مدخلات البحث أو الصفحة غير صالحة')])]
#[OA\Post(path: '/v1/customers', operationId: 'customersStore', summary: 'إنشاء عميل', tags: ['Customers'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم الإنشاء')])]
#[OA\Get(path: '/v1/customers/{customer}', operationId: 'customersShow', summary: 'عرض عميل وحسابه', tags: ['Customers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'customer', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل العميل')])]
#[OA\Put(path: '/v1/customers/{customer}', operationId: 'customersUpdatePut', summary: 'تعديل عميل', tags: ['Customers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'customer', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Patch(path: '/v1/customers/{customer}', operationId: 'customersUpdatePatch', summary: 'تعديل جزئي لعميل', tags: ['Customers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'customer', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Delete(path: '/v1/customers/{customer}', operationId: 'customersDestroy', summary: 'حذف عميل', tags: ['Customers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'customer', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تم الحذف')])]
#[OA\Post(path: '/v1/customers/{customer}/payments', operationId: 'customerPaymentsStore', summary: 'تسجيل دفعة عميل', tags: ['Customers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'customer', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم تسجيل الدفعة')])]
#[OA\Get(path: '/v1/suppliers', operationId: 'suppliersIndex', summary: 'عرض الموردين', tags: ['Suppliers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'search', in: 'query', description: 'بحث بالاسم أو الشركة أو الهاتف أو البريد أو الرقم الضريبي', schema: new OA\Schema(type: 'string', maxLength: 100)), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 25))], responses: [new OA\Response(response: 200, description: 'قائمة الموردين مع بيانات الصفحات'), new OA\Response(response: 422, description: 'مدخلات البحث أو الصفحة غير صالحة')])]
#[OA\Post(path: '/v1/suppliers', operationId: 'suppliersStore', summary: 'إنشاء مورد', tags: ['Suppliers'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم الإنشاء')])]
#[OA\Get(path: '/v1/suppliers/{supplier}', operationId: 'suppliersShow', summary: 'عرض مورد وحسابه', tags: ['Suppliers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'supplier', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل المورد')])]
#[OA\Put(path: '/v1/suppliers/{supplier}', operationId: 'suppliersUpdatePut', summary: 'تعديل مورد', tags: ['Suppliers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'supplier', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Patch(path: '/v1/suppliers/{supplier}', operationId: 'suppliersUpdatePatch', summary: 'تعديل جزئي لمورد', tags: ['Suppliers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'supplier', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Delete(path: '/v1/suppliers/{supplier}', operationId: 'suppliersDestroy', summary: 'حذف مورد', tags: ['Suppliers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'supplier', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تم الحذف')])]
#[OA\Post(path: '/v1/suppliers/{supplier}/payments', operationId: 'supplierPaymentsStore', summary: 'تسجيل دفعة مورد', tags: ['Suppliers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'supplier', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم تسجيل الدفعة')])]
#[OA\Get(path: '/v1/orders', operationId: 'ordersIndex', summary: 'عرض فواتير البيع', tags: ['Sales'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'customer_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'due_only', in: 'query', description: 'القيمة 1 للفواتير ذات المبلغ المتبقي فقط', schema: new OA\Schema(type: 'integer', enum: [0, 1])), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 20))], responses: [new OA\Response(response: 200, description: 'قائمة الفواتير'), new OA\Response(response: 422, description: 'فلاتر غير صالحة')])]
#[OA\Post(path: '/v1/orders', operationId: 'ordersStore', summary: 'إتمام عملية بيع', tags: ['Sales'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم إنشاء الفاتورة'), new OA\Response(response: 409, description: 'تعارض في المخزون أو الوردية')])]
#[OA\Get(path: '/v1/orders/{order}', operationId: 'ordersShow', summary: 'عرض تفاصيل فاتورة', tags: ['Sales'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'order', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل الفاتورة')])]
#[OA\Post(path: '/v1/orders/{order}/returns', operationId: 'orderReturnsStore', summary: 'إرجاع جزئي أو كامل', tags: ['Sales'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'order', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم الإرجاع')])]
#[OA\Get(path: '/v1/pos/reference-data', operationId: 'posReferenceData', summary: 'بيانات شاشة نقطة البيع', tags: ['Sales'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'warehouse_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'البيانات المرجعية')])]
#[OA\Get(path: '/v1/pos/products', operationId: 'posProducts', summary: 'عرض المنتجات المتاحة للبيع', tags: ['Sales'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'warehouse_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid', nullable: true)), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 10, maximum: 100))], responses: [new OA\Response(response: 200, description: 'قائمة المنتجات المتاحة للبيع')])]
#[OA\Get(path: '/v1/purchase-orders', operationId: 'purchaseOrdersIndex', summary: 'عرض أوامر الشراء', tags: ['Purchases'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'قائمة أوامر الشراء')])]
#[OA\Post(path: '/v1/purchase-orders', operationId: 'purchaseOrdersStore', summary: 'إنشاء أمر شراء', tags: ['Purchases'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم الإنشاء')])]
#[OA\Get(path: '/v1/purchase-orders/{purchaseOrder}', operationId: 'purchaseOrdersShow', summary: 'عرض أمر شراء', tags: ['Purchases'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'purchaseOrder', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل أمر الشراء')])]
#[OA\Put(path: '/v1/purchase-orders/{purchaseOrder}', operationId: 'purchaseOrdersUpdate', summary: 'تعديل مسودة أمر شراء', tags: ['Purchases'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'purchaseOrder', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم تعديل المسودة'), new OA\Response(response: 409, description: 'لا يمكن تعديل أمر غير مسودة')])]
#[OA\Delete(path: '/v1/purchase-orders/{purchaseOrder}', operationId: 'purchaseOrdersDestroy', summary: 'حذف مسودة أمر شراء', tags: ['Purchases'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'purchaseOrder', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 204, description: 'تم حذف المسودة'), new OA\Response(response: 409, description: 'لا يمكن حذف أمر غير مسودة')])]
#[OA\Post(path: '/v1/purchase-orders/{purchaseOrder}/send', operationId: 'purchaseOrdersSend', summary: 'إرسال أمر شراء', tags: ['Purchases'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'purchaseOrder', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تم الإرسال')])]
#[OA\Post(path: '/v1/purchase-orders/{purchaseOrder}/cancel', operationId: 'purchaseOrdersCancel', summary: 'إلغاء أمر شراء', tags: ['Purchases'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'purchaseOrder', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم الإلغاء')])]
#[OA\Post(path: '/v1/purchase-orders/{purchaseOrder}/receipts', operationId: 'goodsReceiptsStore', summary: 'استلام بضاعة وتحديث المخزون', tags: ['Purchases'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'purchaseOrder', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم الاستلام')])]
#[OA\Post(path: '/v1/shifts/open', operationId: 'shiftsOpen', summary: 'فتح وردية', tags: ['Shifts'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم فتح الوردية')])]
#[OA\Get(path: '/v1/shifts/last-closed', operationId: 'shiftsLastClosed', summary: 'آخر وردية مغلقة للصندوق', tags: ['Shifts'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'register_id', in: 'query', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'بيانات آخر وردية مغلقة أو null'), new OA\Response(response: 422, description: 'معرف الصندوق غير صالح')])]
#[OA\Post(path: '/v1/shifts/{shift}/cash-in', operationId: 'shiftsCashIn', summary: 'إيداع نقدي', tags: ['Shifts'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'shift', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم الإيداع')])]
#[OA\Post(path: '/v1/shifts/{shift}/cash-out', operationId: 'shiftsCashOut', summary: 'سحب نقدي', tags: ['Shifts'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'shift', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم السحب')])]
#[OA\Get(path: '/v1/shifts/{shift}/summary', operationId: 'shiftsSummary', summary: 'ملخص النقد بالدولار للمالك أو الأدمن', tags: ['Shifts'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'shift', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'data: currency, opening_cash, cash_payments, cash_refunds, cash_in, cash_out, expected_cash'), new OA\Response(response: 403, description: 'غير مسموح')])]
#[OA\Post(path: '/v1/shifts/{shift}/close', operationId: 'shiftsClose', summary: 'إغلاق وردية', description: 'النقد بالدولار. يجب تفسير أي فرق، والفرق المطلق فوق 50 يتطلب دور Admin وسبب تجاوز. تسجيل الخروج لا يغلق الوردية.', tags: ['Shifts'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'shift', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object', required: ['closing_cash'], properties: [new OA\Property(property: 'closing_cash', type: 'number', minimum: 0), new OA\Property(property: 'closing_notes', type: 'string'), new OA\Property(property: 'admin_override_reason', type: 'string')])), responses: [new OA\Response(response: 200, description: 'تم إغلاق الوردية'), new OA\Response(response: 409, description: 'رفض قاعدة عمل'), new OA\Response(response: 422, description: 'بيانات ناقصة أو غير صالحة')])]
#[OA\Get(path: '/v1/reports/overview', operationId: 'reportsOverview', summary: 'ملخص التقارير', tags: ['Reports'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'ملخص التقارير')])]
#[OA\Get(path: '/v1/reports/sales', operationId: 'reportsSales', summary: 'تقرير المبيعات', tags: ['Reports'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'تقرير المبيعات')])]
#[OA\Get(path: '/v1/reports/profit', operationId: 'reportsProfit', summary: 'تقرير الأرباح', tags: ['Reports'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'تقرير الأرباح')])]
#[OA\Get(path: '/v1/reports/products', operationId: 'reportsProducts', summary: 'المنتجات الأكثر مبيعاً', tags: ['Reports'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'تقرير المنتجات')])]
#[OA\Get(path: '/v1/reports/customers', operationId: 'reportsCustomers', summary: 'أفضل العملاء وربح كل عميل', tags: ['Reports'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'تقرير العملاء')])]
#[OA\Get(path: '/v1/users', operationId: 'usersIndex', summary: 'عرض المستخدمين', tags: ['Users'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'قائمة المستخدمين')])]
#[OA\Post(path: '/v1/users', operationId: 'usersStore', summary: 'إنشاء مستخدم مع دوره', tags: ['Users'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم الإنشاء')])]
#[OA\Get(path: '/v1/users/{user}', operationId: 'usersShow', summary: 'عرض مستخدم', tags: ['Users'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'user', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل المستخدم')])]
#[OA\Put(path: '/v1/users/{user}', operationId: 'usersUpdatePut', summary: 'تعديل مستخدم', tags: ['Users'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'user', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Patch(path: '/v1/users/{user}', operationId: 'usersUpdatePatch', summary: 'تعديل جزئي لمستخدم', tags: ['Users'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'user', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Delete(path: '/v1/users/{user}', operationId: 'usersDestroy', summary: 'حذف مستخدم', tags: ['Users'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'user', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تم الحذف')])]
#[OA\Get(path: '/v1/roles', operationId: 'rolesIndex', summary: 'عرض الأدوار', tags: ['Roles'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'قائمة الأدوار')])]
#[OA\Post(path: '/v1/roles', operationId: 'rolesStore', summary: 'إنشاء دور وصلاحياته', tags: ['Roles'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم الإنشاء')])]
#[OA\Get(path: '/v1/roles/{role}', operationId: 'rolesShow', summary: 'عرض دور', tags: ['Roles'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'role', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل الدور')])]
#[OA\Put(path: '/v1/roles/{role}', operationId: 'rolesUpdatePut', summary: 'تعديل دور', tags: ['Roles'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'role', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Patch(path: '/v1/roles/{role}', operationId: 'rolesUpdatePatch', summary: 'تعديل جزئي لدور', tags: ['Roles'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'role', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Delete(path: '/v1/roles/{role}', operationId: 'rolesDestroy', summary: 'حذف دور', tags: ['Roles'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'role', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تم الحذف')])]
#[OA\Get(path: '/v1/permissions', operationId: 'permissionsIndex', summary: 'عرض الصلاحيات', description: 'مجموعات صلاحيات؛ كل عنصر يتضمن id وkey الثابت وname_ar وdescription_ar. تتضمن استجابات الأدوار أيضًا name_ar وdescription_ar مع بقاء name البرمجي كما هو.', tags: ['Roles'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'قائمة الصلاحيات')])]
#[OA\Get(path: '/v1/goods-receipts', operationId: 'goodsReceiptsIndex', summary: 'عرض سندات استلام المشتريات', tags: ['Purchases'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'قائمة سندات الاستلام')])]
#[OA\Get(path: '/v1/goods-receipts/{goodsReceipt}', operationId: 'goodsReceiptsShow', summary: 'عرض تفاصيل سند استلام', tags: ['Purchases'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'goodsReceipt', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل سند الاستلام')])]
#[OA\Get(path: '/v1/suppliers/{supplier}/ledger', operationId: 'supplierLedgerIndex', summary: 'كشف حساب المورد', tags: ['Suppliers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'supplier', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'قيود حساب المورد')])]
#[OA\Get(path: '/v1/suppliers/{supplier}/payments', operationId: 'supplierPaymentsIndex', summary: 'مدفوعات المورد', tags: ['Suppliers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'supplier', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'قائمة مدفوعات المورد')])]
#[OA\Get(path: '/v1/settings/public', operationId: 'settingsPublic', summary: 'الإعدادات العامة', tags: ['Settings'], responses: [new OA\Response(response: 200, description: 'الإعدادات العامة')])]
#[OA\Get(path: '/v1/settings', operationId: 'settingsIndex', summary: 'كل إعدادات النظام', tags: ['Settings'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'قائمة الإعدادات')])]
#[OA\Put(path: '/v1/settings', operationId: 'settingsBulkUpdate', summary: 'تعديل مجموعة من الإعدادات', tags: ['Settings'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'الإعدادات بعد التعديل'), new OA\Response(response: 422, description: 'قيم إعدادات غير صالحة')])]
#[OA\Put(path: '/v1/settings/{setting}', operationId: 'settingsUpdate', summary: 'تعديل إعداد', tags: ['Settings'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'setting', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم التعديل')])]
#[OA\Get(path: '/v1/warehouses', operationId: 'warehousesIndex', summary: 'عرض المستودعات', tags: ['Warehouses'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'قائمة المستودعات')])]
#[OA\Get(path: '/v1/warehouses/{warehouse}', operationId: 'warehousesShow', summary: 'عرض مستودع', tags: ['Warehouses'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'warehouse', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل المستودع'), new OA\Response(response: 404, description: 'المستودع غير موجود')])]
#[OA\Get(path: '/v1/exchange-rate', operationId: 'exchangeRateIndex', summary: 'أسعار الصرف الحالية', tags: ['Settings'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'أسعار الصرف المدعومة')])]
#[OA\Post(path: '/v1/exchange-rate/refresh', operationId: 'exchangeRateRefresh', summary: 'تحديث أسعار الصرف', tags: ['Settings'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'الأسعار المحدثة'), new OA\Response(response: 502, description: 'تعذر جلب الأسعار')])]
#[OA\Get(path: '/v1/exchange-rate/{currency}', operationId: 'exchangeRateShow', summary: 'عرض سعر صرف عملة', tags: ['Settings'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'currency', in: 'path', required: true, schema: new OA\Schema(type: 'string', minLength: 3, maxLength: 3))], responses: [new OA\Response(response: 200, description: 'سعر الصرف'), new OA\Response(response: 404, description: 'العملة غير مدعومة')])]
#[OA\Post(path: '/v1/payment/create-intent', operationId: 'paymentCreateIntent', summary: 'إنشاء Stripe PaymentIntent', tags: ['Payments'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'client_secret لإكمال الدفع في الواجهة'), new OA\Response(response: 422, description: 'المبلغ أو إعدادات Stripe غير صالحة'), new OA\Response(response: 502, description: 'رفض Stripe الطلب')])]
#[OA\Get(path: '/v1/products/reference-data', operationId: 'productsReferenceData', summary: 'البيانات المرجعية لنموذج المنتج', tags: ['Products'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'الوحدات والتصنيفات والضرائب والمستودعات')])]
#[OA\Get(path: '/v1/inventory/balances', operationId: 'inventoryBalancesIndex', summary: 'أرصدة المخزون مع البحث والفلاتر', tags: ['Inventory'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'أرصدة المخزون')])]
#[OA\Get(path: '/v1/inventory/low-stock', operationId: 'inventoryLowStock', summary: 'المنتجات التي بلغت حد إعادة الطلب', tags: ['Inventory'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'تنبيهات المخزون المنخفض')])]
#[OA\Get(path: '/v1/inventory/movements', operationId: 'stockMovementsIndex', summary: 'دفتر حركات المخزون', tags: ['Inventory'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'حركات المخزون')])]
#[OA\Get(path: '/v1/stock-movements', operationId: 'stockMovementsLedgerIndex', summary: 'عرض وتصفية سجل حركات المخزون', tags: ['Inventory'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'search', in: 'query', schema: new OA\Schema(type: 'string', maxLength: 100)), new OA\Parameter(name: 'warehouse_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'product_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'user_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'movement_type', in: 'query', schema: new OA\Schema(type: 'string')), new OA\Parameter(name: 'from', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')), new OA\Parameter(name: 'to', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')), new OA\Parameter(name: 'all', in: 'query', schema: new OA\Schema(type: 'boolean')), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 10, maximum: 100, default: 25))], responses: [new OA\Response(response: 200, description: 'حركات المخزون مع pagination أو جميع السجلات عند all=1'), new OA\Response(response: 422, description: 'فلاتر غير صالحة')])]
#[OA\Put(path: '/v1/inventory/balances/{inventoryBalance}/reorder-level', operationId: 'inventoryReorderLevelUpdate', summary: 'تعديل حد إعادة الطلب', tags: ['Inventory'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'inventoryBalance', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم تعديل الحد')])]
#[OA\Post(path: '/v1/inventory/adjustments', operationId: 'inventoryAdjustmentsStore', summary: 'تسوية الرصيد إلى كمية فعلية', tags: ['Inventory'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تمت التسوية'), new OA\Response(response: 409, description: 'تعارض مع قواعد المخزون')])]
#[OA\Post(path: '/v1/inventory/damages', operationId: 'inventoryDamagesStore', summary: 'تسجيل كمية تالفة', tags: ['Inventory'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم تسجيل التالف')])]
#[OA\Post(path: '/v1/inventory/transfers', operationId: 'inventoryTransfersStore', summary: 'تحويل مخزون بين مستودعين', tags: ['Inventory'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'حركتا إخراج وإدخال مترابطتان')])]
#[OA\Get(path: '/v1/inventory-counts', operationId: 'inventoryCountsIndex', summary: 'عرض عمليات الجرد', tags: ['Inventory Counts'], security: [['sanctum' => []]], responses: [new OA\Response(response: 200, description: 'قائمة عمليات الجرد')])]
#[OA\Post(path: '/v1/inventory-counts', operationId: 'inventoryCountsStore', summary: 'بدء جرد جديد والتقاط الرصيد المتوقع', tags: ['Inventory Counts'], security: [['sanctum' => []]], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 201, description: 'تم بدء الجرد'), new OA\Response(response: 409, description: 'يوجد جرد نشط للمستودع')])]
#[OA\Get(path: '/v1/inventory-counts/{inventoryCount}', operationId: 'inventoryCountsShow', summary: 'عرض تفاصيل الجرد', tags: ['Inventory Counts'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'inventoryCount', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تفاصيل وبنود الجرد')])]
#[OA\Put(path: '/v1/inventory-counts/{inventoryCount}/items', operationId: 'inventoryCountItemsUpdate', summary: 'تسجيل الكميات المعدودة', tags: ['Inventory Counts'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'inventoryCount', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم حفظ العد')])]
#[OA\Post(path: '/v1/inventory-counts/{inventoryCount}/review', operationId: 'inventoryCountsReview', summary: 'إغلاق الإدخال وتحويل الجرد للمراجعة', tags: ['Inventory Counts'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'inventoryCount', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'أصبح الجرد قيد المراجعة')])]
#[OA\Post(path: '/v1/inventory-counts/{inventoryCount}/apply', operationId: 'inventoryCountsApply', summary: 'اعتماد فروقات الجرد وتحديث المخزون', tags: ['Inventory Counts'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'inventoryCount', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], responses: [new OA\Response(response: 200, description: 'تم اعتماد الجرد'), new OA\Response(response: 409, description: 'تغير المخزون بعد بدء الجرد')])]
#[OA\Post(path: '/v1/inventory-counts/{inventoryCount}/cancel', operationId: 'inventoryCountsCancel', summary: 'إلغاء جرد غير مطبق', tags: ['Inventory Counts'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'inventoryCount', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))], requestBody: new OA\RequestBody(ref: '#/components/requestBodies/JsonBody'), responses: [new OA\Response(response: 200, description: 'تم إلغاء الجرد')])]
#[OA\Schema(
    schema: 'AuditLog', type: 'object',
    properties: [
        new OA\Property(property: 'id', type: 'string', format: 'uuid'),
        new OA\Property(property: 'user_id', type: 'string', format: 'uuid', nullable: true),
        new OA\Property(property: 'user', type: 'object', nullable: true, properties: [new OA\Property(property: 'id', type: 'string', format: 'uuid'), new OA\Property(property: 'name', type: 'string')]),
        new OA\Property(property: 'action', type: 'string', example: 'update'),
        new OA\Property(property: 'entity_type', type: 'string', example: 'App\\Models\\Product'),
        new OA\Property(property: 'entity_id', type: 'string', format: 'uuid', nullable: true),
        new OA\Property(property: 'old_values', type: 'object', nullable: true, additionalProperties: true, description: 'القيم السابقة؛ الحقول الحساسة محجوبة بقيمة [REDACTED].'),
        new OA\Property(property: 'new_values', type: 'object', nullable: true, additionalProperties: true, description: 'القيم الجديدة؛ الحقول الحساسة محجوبة بقيمة [REDACTED].'),
        new OA\Property(property: 'logged_at', type: 'string', format: 'date-time'),
    ],
)]
#[OA\Get(
    path: '/v1/audit-logs', operationId: 'auditLogsIndex', tags: ['Audit Logs'],
    summary: 'عرض سجل التدقيق وتصفيته',
    description: 'يتطلب audit_logs.view أو دور Admin. القراءة لا تنشئ سجل تدقيق. الترتيب logged_at ثم id تنازليًا. from/to شاملان لليوم ضمن توقيت التطبيق. لا تتوفر عمليات تعديل أو حذف للسجل.',
    security: [['sanctum' => []]],
    parameters: [
        new OA\Parameter(name: 'user_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid')),
        new OA\Parameter(name: 'action', in: 'query', schema: new OA\Schema(type: 'string', maxLength: 64, pattern: '^[a-z][a-z0-9_]*$')),
        new OA\Parameter(name: 'entity_type', in: 'query', schema: new OA\Schema(type: 'string', maxLength: 255), example: 'App\\Models\\Product'),
        new OA\Parameter(name: 'entity_id', in: 'query', schema: new OA\Schema(type: 'string', format: 'uuid')),
        new OA\Parameter(name: 'from', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')),
        new OA\Parameter(name: 'to', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')),
        new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1)),
        new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100, default: 25)),
    ],
    responses: [
        new OA\Response(response: 200, description: 'سجل منقح مع pagination', content: new OA\JsonContent(type: 'object', properties: [
            new OA\Property(property: 'data', type: 'array', items: new OA\Items(ref: '#/components/schemas/AuditLog')),
            new OA\Property(property: 'links', type: 'object'), new OA\Property(property: 'meta', type: 'object'),
        ])),
        new OA\Response(response: 401, description: 'يلزم تسجيل الدخول'),
        new OA\Response(response: 403, description: 'صلاحية غير كافية أو يلزم تغيير كلمة المرور'),
        new OA\Response(response: 422, description: 'فلاتر غير صالحة؛ تفاصيل الحقول في errors'),
    ],
)]
#[OA\Get(
    path: '/v1/audit-logs/{auditLog}', operationId: 'auditLogsShow', tags: ['Audit Logs'], summary: 'عرض تفاصيل عملية مسجلة',
    description: 'يتطلب audit_logs.view أو دور Admin. عرض التفاصيل مسجل في التدقيق. لا يعرض عناوين IP أو user-agent أو أسرار القيم القديمة والجديدة.',
    security: [['sanctum' => []]],
    parameters: [new OA\Parameter(name: 'auditLog', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))],
    responses: [
        new OA\Response(response: 200, description: 'تفاصيل السجل المنقحة', content: new OA\JsonContent(type: 'object', properties: [new OA\Property(property: 'data', ref: '#/components/schemas/AuditLog')])),
        new OA\Response(response: 401, description: 'يلزم تسجيل الدخول'),
        new OA\Response(response: 403, description: 'صلاحية غير كافية أو يلزم تغيير كلمة المرور'),
        new OA\Response(response: 404, description: 'السجل غير موجود'),
    ],
)]
#[OA\Post(
    path: '/v1/shifts/{shift}/force-close', operationId: 'shiftsForceClose', tags: ['Shifts'], summary: 'إغلاق وردية بالقوة بواسطة مدير النظام',
    description: 'يتطلب دور Admin؛ صلاحية shifts.close وحدها لا تكفي. يجب إدخال سبب الإغلاق والنقد الفعلي.',
    security: [['sanctum' => []]],
    parameters: [new OA\Parameter(name: 'shift', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid'))],
    requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: 'object', required: ['closing_cash', 'reason'], properties: [
        new OA\Property(property: 'closing_cash', type: 'number', minimum: 0), new OA\Property(property: 'reason', type: 'string'),
    ])),
    responses: [new OA\Response(response: 200, description: 'تم إغلاق الوردية'), new OA\Response(response: 401, description: 'يلزم تسجيل الدخول'), new OA\Response(response: 403, description: 'يتطلب دور مدير النظام'), new OA\Response(response: 404, description: 'الوردية غير موجودة'), new OA\Response(response: 409, description: 'تعارض مع حالة الوردية'), new OA\Response(response: 422, description: 'بيانات غير صالحة')],
)]
#[OA\Get(path: '/v1/customers/{customer}/statement', operationId: 'customersStatement', summary: 'كشف حساب العميل وحركات الحساب الآجل', tags: ['Customers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'customer', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100))], responses: [new OA\Response(response: 200, description: 'حركات مرتبة زمنيًا مع المدين والدائن والرصيد المحفوظ، وsummary لإجمالي الفواتير والمدفوع والمستحق ورصيد الحساب'), new OA\Response(response: 401, description: 'يلزم تسجيل الدخول'), new OA\Response(response: 403, description: 'الصلاحية غير متاحة'), new OA\Response(response: 404, description: 'العميل غير موجود'), new OA\Response(response: 422, description: 'رقم الصفحة أو حجمها غير صالح')])]
#[OA\Get(path: '/v1/suppliers/{supplier}/products', operationId: 'supplierProductsIndex', summary: 'منتجات المورد المرتبطة', tags: ['Suppliers'], security: [['sanctum' => []]], parameters: [new OA\Parameter(name: 'supplier', in: 'path', required: true, schema: new OA\Schema(type: 'string', format: 'uuid')), new OA\Parameter(name: 'search', in: 'query', schema: new OA\Schema(type: 'string', maxLength: 100)), new OA\Parameter(name: 'page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1)), new OA\Parameter(name: 'per_page', in: 'query', schema: new OA\Schema(type: 'integer', minimum: 1, maximum: 100))], responses: [new OA\Response(response: 200, description: 'روابط منتجات المورد المحدد فقط؛ التكلفة تتطلب صلاحية عرض البيانات المالية'), new OA\Response(response: 401, description: 'يلزم تسجيل الدخول'), new OA\Response(response: 403, description: 'الصلاحية غير متاحة'), new OA\Response(response: 404, description: 'المورد غير موجود'), new OA\Response(response: 422, description: 'فلاتر غير صالحة')])]
class OpenApi {}
