<x-layouts.app title="التقارير والتحليلات" subtitle="تحليل المبيعات والربحية والعملاء والمنتجات ضمن فترة قابلة للتخصيص">
    @php
        $summary = $overview['summary'];
        $maxTrend = max(1, collect($overview['trend'])->max(fn ($point) => max((float) $point['net_sales'], (float) $point['gross_profit'])) ?? 1);
    @endphp

    <form method="GET" action="{{ route('reports.index') }}" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
            <label class="text-sm font-bold text-slate-700">من تاريخ<input name="from" type="date" value="{{ $filters['from'] }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 outline-none focus:border-brand-500 focus:bg-white"></label>
            <label class="text-sm font-bold text-slate-700">إلى تاريخ<input name="to" type="date" value="{{ $filters['to'] }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 outline-none focus:border-brand-500 focus:bg-white"></label>
            <label class="text-sm font-bold text-slate-700">المخزن<select name="warehouse_id" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 outline-none focus:border-brand-500 focus:bg-white"><option value="">كل المخازن</option>@foreach ($warehouses as $warehouse)<option value="{{ $warehouse->id }}" @selected(($filters['warehouse_id'] ?? '') === $warehouse->id)>{{ $warehouse->name }}</option>@endforeach</select></label>
            <label class="text-sm font-bold text-slate-700">العميل<select name="customer_id" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 outline-none focus:border-brand-500 focus:bg-white"><option value="">كل العملاء</option>@foreach ($customerOptions as $customer)<option value="{{ $customer->id }}" @selected(($filters['customer_id'] ?? '') === $customer->id)>{{ $customer->name }}</option>@endforeach</select></label>
            <label class="text-sm font-bold text-slate-700">الكاشير<select name="user_id" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 outline-none focus:border-brand-500 focus:bg-white"><option value="">كل المستخدمين</option>@foreach ($cashiers as $cashier)<option value="{{ $cashier->id }}" @selected(($filters['user_id'] ?? '') === $cashier->id)>{{ $cashier->full_name }}</option>@endforeach</select></label>
            <label class="text-sm font-bold text-slate-700">طريقة الدفع<select name="payment_method_id" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 outline-none focus:border-brand-500 focus:bg-white"><option value="">كل طرق الدفع</option>@foreach ($paymentMethods as $method)<option value="{{ $method->id }}" @selected(($filters['payment_method_id'] ?? '') === $method->id)>{{ $method->name }}</option>@endforeach</select></label>
            <label class="text-sm font-bold text-slate-700">حالة الفاتورة<select name="status" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 outline-none focus:border-brand-500 focus:bg-white"><option value="">كل الحالات</option>@foreach (['completed' => 'مكتملة', 'partially_refunded' => 'مرتجع جزئي', 'refunded' => 'مرتجعة بالكامل', 'cancelled' => 'ملغاة'] as $value => $label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></label>
            <label class="text-sm font-bold text-slate-700">بحث في الفواتير<input name="search" type="search" value="{{ $filters['search'] ?? '' }}" placeholder="رقم الفاتورة أو اسم العميل" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 outline-none focus:border-brand-500 focus:bg-white"></label>
        </div>
        <div class="mt-5 flex flex-wrap gap-3"><button type="submit" class="rounded-xl bg-brand-500 px-6 py-2.5 text-sm font-black text-white hover:bg-brand-600">تطبيق الفلاتر</button><a href="{{ route('reports.index') }}" class="rounded-xl border border-slate-200 bg-white px-6 py-2.5 text-sm font-black text-slate-700 hover:bg-slate-50">إعادة الضبط</a></div>
    </form>

    <section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach ([
            ['label' => 'صافي المبيعات', 'value' => number_format((float) $summary['net_sales'], 2).' $', 'sub' => 'إجمالي قبل الضريبة'],
            ['label' => 'الربح الإجمالي', 'value' => number_format((float) $summary['gross_profit'], 2).' $', 'sub' => 'هامش '.$summary['gross_margin_percentage'].'%'],
            ['label' => 'عدد الفواتير', 'value' => number_format($summary['orders_count']), 'sub' => 'متوسط '.$summary['average_order_value'].' $'],
            ['label' => 'المرتجعات', 'value' => number_format((float) $summary['refunds'], 2).' $', 'sub' => number_format($summary['returns_count']).' عملية إرجاع'],
            ['label' => 'الخصومات', 'value' => number_format((float) $summary['discounts'], 2).' $', 'sub' => 'خصومات مطبقة'],
            ['label' => 'تكلفة البضاعة', 'value' => number_format((float) $summary['cost_of_goods_sold'], 2).' $', 'sub' => 'COGS الصافية'],
            ['label' => 'صافي الضرائب', 'value' => number_format((float) $summary['net_tax'], 2).' $', 'sub' => 'بعد ضرائب المرتجعات'],
            ['label' => 'الكمية الصافية', 'value' => number_format((float) $summary['net_quantity'], 3), 'sub' => 'بعد الكميات المرتجعة'],
        ] as $metric)
            <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-bold text-slate-500">{{ $metric['label'] }}</p><p class="mt-3 text-2xl font-black text-slate-950">{{ $metric['value'] }}</p><p class="mt-2 text-xs text-slate-500">{{ $metric['sub'] }}</p></article>
        @endforeach
    </section>

    <section class="mt-6 grid gap-6 xl:grid-cols-3">
        <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2">
            <header><h2 class="font-black">اتجاه المبيعات والربح</h2><p class="mt-1 text-sm text-slate-500">يعتمد الإرجاع على تاريخ حدوثه وليس تاريخ الفاتورة الأصلية</p></header>
            <div class="mt-6 flex h-64 items-end gap-2 overflow-x-auto border-b border-slate-200 pb-2">
                @forelse ($overview['trend'] as $point)
                    <div class="flex min-w-8 flex-1 items-end justify-center gap-0.5" title="{{ $point['date'] }} | مبيعات {{ $point['net_sales'] }} | ربح {{ $point['gross_profit'] }}"><span class="w-2 rounded-t bg-emerald-400" style="height: {{ max(3, ((float) $point['net_sales'] / $maxTrend) * 220) }}px"></span><span class="w-2 rounded-t bg-blue-500" style="height: {{ max(3, ((float) $point['gross_profit'] / $maxTrend) * 220) }}px"></span></div>
                @empty
                    <p class="m-auto text-sm text-slate-500">لا توجد بيانات.</p>
                @endforelse
            </div>
        </article>
        <article class="rounded-2xl border border-slate-200 bg-slate-950 p-5 text-white shadow-sm"><p class="text-sm font-bold text-slate-400">مقارنة بالفترة السابقة</p><div class="mt-6 flex flex-col gap-5">@foreach ([['صافي المبيعات', $profit['changes']['net_sales_percentage']], ['الربح الإجمالي', $profit['changes']['gross_profit_percentage']], ['عدد الفواتير', $profit['changes']['orders_percentage']]] as [$label, $change])<div class="flex items-center justify-between gap-3"><span class="text-sm font-bold">{{ $label }}</span><span class="rounded-lg px-3 py-1.5 text-sm font-black {{ (float) $change >= 0 ? 'bg-emerald-500/20 text-emerald-300' : 'bg-rose-500/20 text-rose-300' }}">{{ (float) $change >= 0 ? '+' : '' }}{{ $change }}%</span></div>@endforeach</div><p class="mt-8 border-t border-white/10 pt-4 text-xs leading-6 text-slate-400">الفترة السابقة: {{ $profit['previous_period']['from'] }} — {{ $profit['previous_period']['to'] }}</p></article>
    </section>

    <section class="mt-6 grid gap-6 xl:grid-cols-2">
        <article class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-100 p-5"><h2 class="font-black">أفضل 10 منتجات</h2><p class="mt-1 text-sm text-slate-500">كمية، مبيعات، ربح وهامش</p></header><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-sm"><thead class="bg-slate-50 text-right text-slate-500"><tr><th class="px-5 py-3">المنتج</th><th class="px-5 py-3">الكمية</th><th class="px-5 py-3">المبيعات</th><th class="px-5 py-3">الربح</th><th class="px-5 py-3">الهامش</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($products as $product)<tr><td class="px-5 py-4"><p class="font-bold">{{ $product['product_name'] }}</p><p class="text-xs text-slate-500">{{ $product['sku'] }}</p></td><td class="px-5 py-4">{{ $product['net_quantity'] }}</td><td class="px-5 py-4">{{ $product['net_sales'] }} $</td><td class="px-5 py-4 font-black text-emerald-700">{{ $product['gross_profit'] }} $</td><td class="px-5 py-4">{{ $product['gross_margin_percentage'] }}%</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">لا توجد بيانات.</td></tr>@endforelse</tbody></table></div></article>
        <article class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-100 p-5"><h2 class="font-black">أفضل 10 عملاء</h2><p class="mt-1 text-sm text-slate-500">صافي المشتريات والربح الناتج</p></header><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-sm"><thead class="bg-slate-50 text-right text-slate-500"><tr><th class="px-5 py-3">العميل</th><th class="px-5 py-3">الفواتير</th><th class="px-5 py-3">المشتريات</th><th class="px-5 py-3">الربح</th><th class="px-5 py-3">المتوسط</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($customers as $customer)<tr><td class="px-5 py-4"><p class="font-bold">{{ $customer['name'] }}</p><p class="text-xs text-slate-500">{{ $customer['phone'] }}</p></td><td class="px-5 py-4">{{ $customer['orders_count'] }}</td><td class="px-5 py-4">{{ $customer['net_sales'] }} $</td><td class="px-5 py-4 font-black text-emerald-700">{{ $customer['gross_profit'] }} $</td><td class="px-5 py-4">{{ $customer['average_order_value'] }} $</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">لا توجد بيانات.</td></tr>@endforelse</tbody></table></div></article>
    </section>

    <section class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <header class="flex flex-col gap-2 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-black">الفواتير ضمن الفترة</h2><p class="mt-1 text-sm text-slate-500">{{ number_format($orders->total()) }} فاتورة مطابقة للفلاتر</p></div><span class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600">النتائج مرتبة من الأحدث</span></header>
        <div class="overflow-x-auto"><table class="w-full min-w-[1000px] text-sm"><thead class="bg-slate-50 text-right text-slate-500"><tr><th class="px-5 py-3">الفاتورة</th><th class="px-5 py-3">التاريخ</th><th class="px-5 py-3">العميل</th><th class="px-5 py-3">الكاشير</th><th class="px-5 py-3">الأصناف</th><th class="px-5 py-3">الإجمالي</th><th class="px-5 py-3">المرتجع</th><th class="px-5 py-3">الدفع</th><th class="px-5 py-3">الحالة</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($orders as $order)<tr><td class="px-5 py-4 font-black">{{ $order->invoice_number }}</td><td class="px-5 py-4 text-slate-500">{{ $order->order_date->format('Y-m-d H:i') }}</td><td class="px-5 py-4">{{ $order->customer?->name ?? 'عميل نقدي' }}</td><td class="px-5 py-4">{{ $order->user->full_name }}</td><td class="px-5 py-4">{{ $order->items_count }}</td><td class="px-5 py-4 font-bold">{{ number_format((float) $order->final_amount, 2) }} $</td><td class="px-5 py-4 text-rose-600">{{ number_format((float) $order->refunded_amount, 2) }} $</td><td class="px-5 py-4">{{ $order->payment_status->value }}</td><td class="px-5 py-4">{{ $order->status->value }}</td></tr>@empty<tr><td colspan="9" class="px-5 py-16 text-center text-slate-500">لا توجد فواتير مطابقة.</td></tr>@endforelse</tbody></table></div>
        <div class="border-t border-slate-100 p-4">{{ $orders->links() }}</div>
    </section>
</x-layouts.app>
